/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type MatchResult = {
  _type: "matchResult";
  round: string;
  date: string;
  opponent: string;
  venue: "\u0414\u043E\u043C\u0430" | "\u0413\u043E\u0441\u0442\u0438";
  goalsFor: number;
  goalsAgainst: number;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  source: string;
  verified?: boolean;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SeasonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "season";
};

export type Story = {
  _id: string;
  _type: "story";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  seasons?: Array<
    {
      _key: string;
    } & SeasonReference
  >;
  source: string;
  verified?: boolean;
};

export type Person = {
  _id: string;
  _type: "person";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  fullName: string;
  slug: Slug;
  roles: Array<string>;
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  source: string;
  verified?: boolean;
};

export type Season = {
  _id: string;
  _type: "season";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  label: string;
  startYear: number;
  slug: Slug;
  competition?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  results?: Array<
    {
      _key: string;
    } & MatchResult
  >;
  source: string;
  verified?: boolean;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | MatchResult
  | Page
  | Slug
  | SeasonReference
  | Story
  | Person
  | Season
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../lib/sanity/queries.ts
// Variable: ALL_SEASONS_QUERY
// Query: *[_type == "season" && verified == true] | order(startYear asc){    _id, label, startYear, "slug": slug.current  }
export type ALL_SEASONS_QUERY_RESULT = Array<{
  _id: string;
  label: string;
  startYear: number;
  slug: string;
}>;

// Source: ../lib/sanity/queries.ts
// Variable: SEASON_BY_SLUG_QUERY
// Query: *[_type == "season" && verified == true && slug.current == $slug][0]{    _id, label, startYear, "slug": slug.current, competition, body,    results[]{ round, date, opponent, venue, goalsFor, goalsAgainst }  }
export type SEASON_BY_SLUG_QUERY_RESULT = {
  _id: string;
  label: string;
  startYear: number;
  slug: string;
  competition: string | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  results: Array<{
    round: string;
    date: string;
    opponent: string;
    venue: "\u0413\u043E\u0441\u0442\u0438" | "\u0414\u043E\u043C\u0430";
    goalsFor: number;
    goalsAgainst: number;
  }> | null;
} | null;

// Source: ../lib/sanity/queries.ts
// Variable: ALL_PEOPLE_QUERY
// Query: *[_type == "person" && verified == true] | order(fullName asc){    _id, fullName, "slug": slug.current, roles  }
export type ALL_PEOPLE_QUERY_RESULT = Array<{
  _id: string;
  fullName: string;
  slug: string;
  roles: Array<string>;
}>;

// Source: ../lib/sanity/queries.ts
// Variable: PERSON_BY_SLUG_QUERY
// Query: *[_type == "person" && verified == true && slug.current == $slug][0]{    _id, fullName, "slug": slug.current, roles, bio  }
export type PERSON_BY_SLUG_QUERY_RESULT = {
  _id: string;
  fullName: string;
  slug: string;
  roles: Array<string>;
  bio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
} | null;

// Source: ../lib/sanity/queries.ts
// Variable: PAGE_BY_SLUG_QUERY
// Query: *[_type == "page" && verified == true && slug.current == $slug][0]{    _id, title, "slug": slug.current, body  }
export type PAGE_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "season" && verified == true] | order(startYear asc){\n    _id, label, startYear, "slug": slug.current\n  }': ALL_SEASONS_QUERY_RESULT;
    '*[_type == "season" && verified == true && slug.current == $slug][0]{\n    _id, label, startYear, "slug": slug.current, competition, body,\n    results[]{ round, date, opponent, venue, goalsFor, goalsAgainst }\n  }': SEASON_BY_SLUG_QUERY_RESULT;
    '*[_type == "person" && verified == true] | order(fullName asc){\n    _id, fullName, "slug": slug.current, roles\n  }': ALL_PEOPLE_QUERY_RESULT;
    '*[_type == "person" && verified == true && slug.current == $slug][0]{\n    _id, fullName, "slug": slug.current, roles, bio\n  }': PERSON_BY_SLUG_QUERY_RESULT;
    '*[_type == "page" && verified == true && slug.current == $slug][0]{\n    _id, title, "slug": slug.current, body\n  }': PAGE_BY_SLUG_QUERY_RESULT;
  }
}
